### ISSUE TITLE
No auto substitution $[mavenRepoLogin] in mvn settings.xml

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#605] opened 2021-09-25 12:15 UTC
### Expected behavior

As a product owner, I want to deploy a preconfigured settings.xml so that the user installing the IDE is asked at installation time to enter username and password for the given repository. This is meant in https://github.com/devonfw/ide-settings/blob/master/devon/conf/.m2/settings.xml that I have to declare variables `$[....]`. "Then devonfw-ide will automatically promt for these variables, encrypt their value and fill it into the placeholder."

### Actual behavior

I have never been asked for the variables to be replaced.
Just a side-mark: For proper configuration https://github.com/devonfw/ide-settings/blob/master/devon/conf/.m2/settings.xml#L22 and https://github.com/devonfw/ide-settings/blob/master/devon/conf/.m2/settings.xml#L65 should have the same name at least to provide a good pre-configured example.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. run download and execute with the powershell command from the website: `Invoke-WebRequest -OutFile devonfw-ide-scripts.tar.gz 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.tools.ide&a=devonfw-ide-scripts&v=LATEST&p=tar.gz'; tar -xvzf .\devonfw-ide-scripts.tar.gz; .\setup.bat`

### Affected version:

* OS: Windows

**Comment by hohwille** [comment] 2022-01-11 16:29
@maybeec thanks for your issue.
If you want you can consider this as a "documentation but" but everything works as designed:
https://github.com/devonfw/ide/blob/f6f3671298f66472e6ffd46a41c22f6a93901ab6/scripts/src/main/resources/scripts/command/mvn#L51

When you use the default settings the replacement of the variables is omitted because:
* we have automated tests and tutorials that would break otherwise
* an end-user only uses the default settings to setup a quick and dirty simple IDE for testing. There he will never need credentials and would be rather confused by this questions.

Simply fork the settings and use the GIT URL of the fork and it should work.

> Just a side-mark: For proper configuration https://github.com/devonfw/ide-settings/blob/master/devon/conf/.m2/settings.xml#L22 and https://github.com/devonfw/ide-settings/blob/master/devon/conf/.m2/settings.xml#L65 should have the same name at least to provide a good pre-configured example.

Also here I disagree: the `devonfw-snapshots` repo is provided for end-users that want to test SNAPSHOT releases of `devon4j`. It does not require any credentials (unless you want to deploy). If you would rename it to `repository` then IMHO your project credentials would IMHO be sent to sonatype what is unintendet for security.

I would rather close this as invlid. Any concerns or new comments?

**Comment by hohwille** [comment] 2022-01-13 08:46
improved docs, hence closing.

**Closed by hohwille** 2022-01-13 08:46 UTC
Labels: bug, invalid, scripts, settings, maven
