### ISSUE TITLE
Eclipse project not imported for workspaces other than main

### ISSUE THREAD

**Issue by andreasrichtercg** [devonfw/ide#518] opened 2021-01-14 15:03 UTC
### Expected behavior

As a developer/architect, 
I want projects to be imported into eclipse workspace for a specific workspace (not "main") defined in <project>.properties,
so that I don't have to import it manually

### Actual behavior
After opening eclipse for other workspace than main (e.g. eclipse-other.bat), no imported project is visible

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create a project properties file in settings/projects/<my-project>.properties
2. Set workspace to "workspace=other"
3. run devon ide update projects

### Affected version: 2020.12

* OS: Windows

**Comment by hohwille** [comment] 2021-01-15 09:10
Thanks for reporting this bug. However, it is a duplicate of #480 that has just been fixed a few days ago. Release is planned for next week...

**Closed by hohwille** 2021-01-15 09:10 UTC
Labels: duplicate
