### ISSUE TITLE
Automate the mirror selection to download eclipse, java etc..

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/ide#627] opened 2021-11-18 14:19 UTC
Java download or Eclipse download mirrors are hard coded in the code currently. Instead of a hard coded mirror, the mirror selection should happen randomly from a list of mirrors. The mirror list can be kept on github.

**Comment by hohwille** [comment] 2021-12-17 18:42
Kind of a duplicate of issue #641.
Issue is resolved, hence closing.

**Closed by hohwille** 2021-12-17 18:42 UTC
Labels: enhancement
