### ISSUE TITLE
notification of errors from ide-urls action - duplicate of #126

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1219] opened 2023-06-27 08:27 UTC
Our github action [update-urls.yml](https://github.com/devonfw/ide/blob/master/.github/workflows/update-urls.yml) logs errors if downloads fail (including download veriifications) but continues successfully also on such errors.
We should add a mechanism to count errors in a structured way and then send a notification with an error report. If there is no error also no notification should be send. My suggestion would be to use an email notification. If we use a public distribution list and want to avoid spam, we can configure it as github secret.
To collect the errors, we we should create a structured error state object and count the errors per tool and edition. We should then also count the success so we could e.g. determine and error rate (e.g. gradle 100% error vs. gradle 1% errors). My first draft suggestion:
* «tool»/«edition»: versions added: 5 failed, 7 succeeded, 13 total, 38,4% error - versions verified: 0 failed, 0 succeeded, 0 total, 0% error

FYI: I pointed that example also to point out a potential division by zero issue before implementation :)

**Comment by ndemirca** [comment] 2024-08-30 09:05
duplicate of https://github.com/devonfw/IDEasy/issues/126, this won't be done!

**Closed** 2024-09-05 08:57 UTC
Labels: duplicate, enhancement, SCM
