### ISSUE TITLE
Symlink of software failed for macOS

### ISSUE THREAD

**Issue by tobka777** [devonfw/ide#1115] opened 2023-04-24 10:20 UTC
### Expected behavior

As a user, I want use java on mac, but it failed to verify installation of java.
The reason is, that the symlink for java is not created.

### Actual behavior

```
*** Setting up java ***
Success: run command mkdir
Starting installation of java in version 8u292b10 to /Users/xxxx/projects/xxxx/software/java
Trying to download java-8u292b10-mac.tar.gz from https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_mac_hotspot_8u292b10.tar.gz
Artifact already exists at /Users/xxxx/Downloads/devonfw-ide/java-8u292b10-mac.tar.gz
To force update please delete the file and run again.
Success: run command tar
Successfully extracted archive java-8u292b10-mac.tar.gz to /Users/xxxx/projects/xxxx/updates/extracted/java
Success: run command mv
Successfully installed java
The software java has been added. You need to rerun 'devon' command without arguments or restart your terminal to update your PATH so the newly installed software will be found.
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.


******** ATTENTION ********
Failed to verify installation of java (java)
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 1
Command 'java setup' failed with exit code 1

******** ATTENTION ********
Failed to run devon java setup
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 1
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install devon `./setup`

### Affected version:

* OS: Mac

**Comment by hohwille** [comment] 2023-04-25 08:58
@tobka777 can you add analysis details? What folder structure was created, what symlink has been created?

**Comment by hohwille** [comment] 2023-05-08 06:58
Can we close this issue or do you have any further details?

**Comment by dendmicap** [comment] 2023-05-08 15:30
I couldn't reproduce the bug on the recent version (2023.04.001) on the mac vm. Seems like it was already fixed.

**Closed by dendmicap** 2023-05-08 15:30 UTC
Labels: bug, macOS
