### ISSUE TITLE
devon.properties ignored when not ending with empty line

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#401] opened 2020-04-20 10:52 UTC
### Expected behavior

As an architect, I want to configure the ide provisioning so that it fits my needs. If I change devon.properties to an illegal format, I should get noticed by the ide setup.

### Actual behavior
I configure the settings/devon.properties and possibly by accident, possibly by intention delete the last empty line. This leads to the behavior, that the devon.properties file is completely ignored without any error on setup.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. clone clean settings
2. make some adjustments, i.e. download custom software
3. remove empty line from settings/devon.properties
4. run setup, which will ignore your changes

### Affected version:

* OS: Windows

**Comment by hohwille** [comment] 2020-04-27 18:59
Duplicate of #394

**Closed by hohwille** 2020-04-27 18:59 UTC
Labels: bug
