### ISSUE TITLE
SonarQube is not working without args

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1248] opened 2023-07-10 12:08 UTC
### Expected behavior

As a devonfw-ide MacOSX user I want to install SonarQube, so that I can use it for my projects.

### Actual behavior
`devon sonar` returns:
`undefined argument`
`devon sonar setup` works fine

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run `devon sonar`

### Comments/Hints:
We could instead of showing "undefined argument" show the help or version.

### Affected version:

* OS: Mac
* devonfw-ide: 2023.07.001-SNAPSHOT

**Comment by hohwille** [comment] 2023-07-10 21:52
Same as #1247 
Besides both issues have nothing to do with MacOS. This is a general usability issue for all operating systems.

**Comment by hohwille** [comment] 2023-07-11 07:47
Duplicate of #1247

**Closed by hohwille** 2023-07-11 07:47 UTC
Labels: bug
