### ISSUE TITLE
Home doc seems outdated

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/ide#264] opened 2019-10-01 15:17 UTC
When reading the [home](https://github.com/devonfw/ide/blob/master/documentation/Home.asciidoc) document, it says:

TL;DR?

1. [download](https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devon-ide-scripts/)
2. extract to `C:\projects\my-project-name` or `/projects/my-project-name`
3. run `setup` script
4. run `eclipse-main` to launch Eclipse or `vscode-main` for Visual Studio code
5. happy hacking!

After following the first 3 steps, I don't see any `eclipse-main` nor `vscode-main`. Most probably that document is outdated.

**Comment by jdiazgon** [comment] 2019-10-03 13:33
I have seen on the code the following lines:

```bash
  echo The devon CLI script has been installed to your windows system.
  echo Now in any new command shell, you can call devon to setup your IDE enviromennt variables.
```
These comments should definitively be on the Home doc.

**Comment by hohwille** [comment] 2019-10-14 13:52
I just reinstalled my devon-ide and after step 3. I got both `eclipse-main` and `vscode-main` in the top-level folder of my IDE. So what is going wrong here?
Maybe you are using a specific settings URL that redefines the `DEVON_IDE_TOOLS` variable (https://github.com/devonfw/ide/blob/master/documentation/variables.asciidoc) - are you doing that in cobigen probably?

For your second comment: IMHO I can not prevent the RTFM syndrome. It is all there in the documentation. "TL;DR" stands for "too long, did not read" what is unfortunately the trend of today. However this is why in that section I write the ultimate minimal steps to get started. So adding the hints you are suggesting also to Home does not make sense to me. Then we would also need to add tons of other information that is all already there in the documentation but the idea of a `Home` site is to give a compact and minimal introduction and link to further sources.
I am happy to receive any kind of PRs to update the documentation, but I can not see how to address this feedback here and IMHO need to close this issue without any change (unless more insights are given to enlighten me).

**Comment by jdiazgon** [comment] 2019-10-14 15:36
> I just reinstalled my devon-ide and after step 3. I got both `eclipse-main` and `vscode-main` in the top-level folder of my IDE. So what is going wrong here?

Have you tested it on Windows? I don't see them.

> Maybe you are using a specific settings URL that redefines the `DEVON_IDE_TOOLS` variable 

I don't think so. I guess I have used the default ones.

> For your second comment: IMHO I can not prevent the RTFM syndrome. 

I understand your point and would be fine for me if you leave it like this.

**Comment by hohwille** [comment] 2019-10-14 20:16
> Have you tested it on Windows? I don't see them.

Yep. But Win10 inside VMWare Fusion on MacOS as I do not have a native windows machine.

I am still very busy this week. Maybe we can have a short screensharing next week and try to reproduce this issue on your machine. If we can do so, I am happy to fix it. As long as I cannot reproduce it, I am quite unable to do so.

**Comment by hohwille** [comment] 2019-11-01 07:53
IMHO this issue was due to other problems discussed in #265.
I will close this issue as invalid. Feel free to reopen with instructions to reproduce if you do not agree.

**Closed** 2019-11-01 07:54 UTC
Labels: documentation, enhancement, invalid
