### ISSUE TITLE
ERROR: missing arguments for doInstall:  https://github.com/devonfw/devon-ide-settings.git devon-ide-settings

### ISSUE THREAD

**Issue by gceasori** [devonfw/ide#271] opened 2019-10-08 09:06 UTC
### Expected behavior

I am not able to install the Devon IDE.  I get the following Error.
Setting up your devon-ide in C:\projects\my-project
scripts/environment-project: line 5: /dev/fd/62: No such file or directory
devon-ide has environment variables have been set for /c/projects/my-project in workspace main
/c/projects/my-project/scripts/environment-project: line 5: /dev/fd/62: No such file or directory
Missing your settings at  and no SETTINGS_URL is defined.
Further details can be found here:
https://github.com/devonfw/devon-ide/wiki/settings
Please contact the technical lead of your project to get the SETTINGS_URL for your project.
In case you just want to test devon-ide you may simply hit return to install default settings.

Settings URL:

******** ATTENTION ********
ERROR: missing arguments for doInstall:  https://github.com/devonfw/devon-ide-settings.git devon-ide-settings
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
The operation completed successfully.
The operation completed successfully.
Setup of devon-ide completed
Press any key to continue . . .

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. I have followed the directions of devon-ide-doc.pdf.
2.- In devon.bat I have forced the variable GIT_HOME. Could be the problem that the necessary variables are not initialized

### Affected version:
Windows
* OS: Windows/Linux/Mac?
* Browser: Chrome/Firefox/Safari?

**Comment by markusschuh** [comment] 2019-10-08 10:43
related to, if not duplicate of #262  I already have marked the #262 as blocker, but it needs somebody to test and implement the proposed solution. (No PR yet)

The `scripts/environment-project: line 5: /dev/fd/62: No such file or directory` stops the correct read of settings, so environment variable values are wrong.

Which results also into the output line:
`Missing your settings at and no SETTINGS_URL is defined.`

The invisible '' after `at` should be handled as a fatal error, I'd say. This empty value causes all kind of follow-up issues - I guess, also the one, you have reported here.

**Comment by hohwille** [comment] 2019-10-14 13:26
IMHO a duplicate of #262. Hence closing. See also PR #274 that should fix the bug.

**Closed by hohwille** 2019-10-14 13:26 UTC
Labels: bug

**Comment by hohwille** [comment] 2019-10-14 13:39
@gceasori thanks for this issue. I have merged PR #274 and just released beta23. It might take a few hours till it is available in maven central. It would be awesome if you could retest with that version and give feedback if the issue is really fixed now (otherwise just reopen this issue).
