### ISSUE TITLE
Expansion of ~ stopped working on windows CMD (M2_HOME not properly set)

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#467] opened 2020-09-21 15:28 UTC
### Expected behavior

As a user, I want to use devonfw-ide on windows so that I can execute maven builds on a devonfw console.
### Actual behavior

M2_REPO is not recognized and thus every mvn command is running on ~/.m2/repository in the current execution path.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Set `export M2_REPO=~/.m2/repository` in devon.properties
2. open a devon cmd
3. run `mvn -X` or `echo %M2_REPO%

### Affected version:

* OS: Windows

**Comment by hohwille** [comment] 2020-09-22 12:37
I do not know if this is blocking you: You can edit the variable and manually replace `~` with something like `C:\Users\«mylogin»`. However, we accept this is a stupid bug that needs to be fixed asap.

**Comment by hohwille** [comment] 2020-09-22 12:41
The bug starts in the code here:
https://github.com/devonfw/ide/blob/306881afd2d924e88d18b7950988e05a39ea96b4/scripts/src/main/resources/scripts/environment-project.bat#L106
So the problem is that this script has been refactored in commit https://github.com/devonfw/ide/commit/ad2cf7218828261f66ec79df20413d3eddb9a126#diff-78672940921d6ea3caa0fafb3281c3b2 but the part to resolve the tilde `~` that is not understood by windows properly was not changed accordingly. So before there where two variables `var` (variable name/key) and `value` (value of the env. variable) and now we only have `line` (entire line of variable assignment).
Hence the code can not work:
https://github.com/devonfw/ide/blob/306881afd2d924e88d18b7950988e05a39ea96b4/scripts/src/main/resources/scripts/environment-project.bat#L107

**Comment by hohwille** [comment] 2020-09-22 12:47
The problem is that windows BAT/CMD (and partially shell-scripting in general) is not a reasonable programming language but something for quick hacks and this really applies to BAT and CMD that is historically grown since many decades.
That is also why we redesigned from `oasp4j-ide` to `devonfw-ide` and reduced the amount of BAT/CMD scripting to an absolute minimum.
Anyhow, not an excuse for my lack in QA when I fixed #395 but introduced this bug here.

I will try to come up with a fix for this issue and replace `~` with the proper value of `%USERPROFILE%` and hopefully manage to do so without breaking something else. In reasonable programming languages replacing a substring in a string with the value of a variable is a trivial one-liner. In BAT/CMD hell this is a real challenge...

**Comment by hohwille** [comment] 2020-09-22 13:17
As expected already replacing a simple `~` with some static text is requiring tons of magic hacks in CMD replacing it with the content of a variable might be the work of a PhD thesis:
https://stackoverflow.com/questions/57610104/how-do-i-escape-tilde-in-batch-file-on-replacing-it-with-a-different-charact

**Comment by hohwille** [comment] 2020-09-22 13:25
Characters like `~`, `*` or `=` are already reserved vor variable replacement syntax in CMD. Furhter there is no such concept of escaping. Maybe I could try to create a loop that iterates the string character by character and thereby appends the resolved string by copying the characters but replacing `~` with `%USERPROFILE%`.
However, we need to read all contents of multiple `devon.properties` files line by line. If that processing is getting much slower the usability will be pain. Maybe we have to implement a native program for windows compiled for x68 architecture and ship it with `devonfw-ide`.
If you have any cool ideas how to fix this easily please help us.

**Comment by hohwille** [comment] 2020-09-22 13:30
I removed `blocker` label als you actually tweaked the default config that does not come with a `~`:
https://github.com/devonfw/ide/blob/f03a5885301047abec244112f9fe5203189ea288/scripts/src/main/resources/scripts/devon.properties#L16

You may also use something like `${HOME}` or `${USERPROFILE}` instead of `~` as a workaround or even easier simply use the hardcoded path to your home directory if you already tweak your `devon.properties`.
Further you can simply stop using this crappy `CMD` and always use git-bash instead that is not affected.

Finally, tools like the `JVM` or `Maven` should already be capable to understand a path starting with `~` and those tools could implement this much easier than us in CMD hacks.
Still looking for a solution but as long as I am lost alone in CMD space I might not be able to fix this quickly...

**Comment by hohwille** [comment] 2020-09-22 13:54
I found that CMD uses `^` as escape character and in some other cases even `\`. It tested all possible scenarios but this does not work in any way with variable replacement.

**Comment by hohwille** [comment] 2020-09-22 15:38
According to maintenance it would be best to support only bash and stop users from using CMD, powershell or cygwin in devonfw-ide.
However, for freedome of usage all major windows shells shall be supported - even though it drives me nuts...
The biggest joke of CMD is that `SHIFT` command does not affect `%*` - see https://ss64.com/nt/shift.html.

**Comment by hohwille** [comment] 2020-09-22 16:22
I just figured out that CMD only supports 2 levels of nesting `if «condition» ( «cmd1» ) else ( «cmd2» )`. As it also does not support `else if` I can not append parameters like this:
```
  if not "%~9" == "" (
    set line=!line! %~3 %~4 %~5 %~6 %~7 %~8 %~9
  ) else (
    if not "%~8" == "" (
      set line=!line! %~3 %~4 %~5 %~6 %~7 %~8
    ) else (
      if not "%~7" == "" (
        set line=!line! %~3 %~4 %~5 %~6 %~7
      ) else (
        if not "%~6" == "" (
          set line=!line! %~3 %~4 %~5 %~6
        ) else (
          if not "%~5" == "" (
            set line=!line! %~3 %~4 %~5
          ) else (
            if not "%~4" == "" (
              set line=!line! %~3 %~4
            ) else (
              if not "%~3" == "" (
                set line=!line! %~3
	          )
	        )
	      )
	    )
	  )
	)
  )
```

**Closed** 2020-09-24 17:00 UTC
Labels: bug, scripts, windows
