### ISSUE TITLE
Epic: Nigthly test for devon IDE and tool installation

### ISSUE THREAD

**Issue by JokeFrels** [devonfw/ide#663] opened 2021-12-27 06:38 UTC
As a devon framework user I want to install the devon IDE and the tools that I need without any difficulties to be able to start right away. Since there can be changes, there should be an automated nightly test with GitHub Actions for the devon IDE and each tool that checks if the tool still can be installed.

**Comment by hohwille** [comment] 2022-01-06 17:37
Some aspects to consider for such automated testing:
* tools to test (java, mvn, eclipse, intellij, vscode, jenkins, node, npm, yarn, jasypt, etc.)
* versions to test per tool (will we only test that currently configured latest default version is working or will we also check specific older versions or even all versions we ever officially used as default in any release of devonfw-ide?)
* plugins (eclipse, intellij, vscode all support plugins - do we want to test this as well? Do we want to test all plugins including those that are disabled with `active=false`?)
* do we only want to test our mirrors or do we want to test various installation features of the devonfw-ide? The latter also includes features such as [custom-tooling](https://github.com/devonfw/ide/blob/master/documentation/software.asciidoc#custom) - see bug #669 or [software-repository](https://github.com/devonfw/ide/blob/master/documentation/software.asciidoc#repository)?

Do not get me wrong: I am happy if we start agile step by step. Everything in this direction is a step forward for better quality. I just wanted to outline that after all testing of devonfw-ide is more tricky that one might think in the first place and we should think early on what we might want to archive on the long run...

**Comment by hohwille** [comment] 2022-05-24 07:11
More or less a duplicate of #691 ?

**Comment by hohwille** [comment] 2023-04-24 15:19
Finally closing as duplicate and #691 was already implemented...

**Closed by hohwille** 2023-04-24 15:19 UTC
Labels: duplicate, Epic
