### ISSUE TITLE
Download of software from SourceTree git bash does not work

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1096] opened 2023-04-13 07:23 UTC
### Expected behavior

As a devonfw-ide user, I want to use my external git bash f.e. from SourceTree so that I can easily update my devon ide software to the required version.

### Actual behavior

Currently the download of Java fails with:
```
curl: (22) The requested URL returned error: 404
Failed to download https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_i686_windows_hotspot_17.0.5_8.zip with exit code 22
```

When I use the git bash from the context menu I get the correct URL though.

`Download of java-17.0.4.1_1-windows.zip from https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4.1%2B1/OpenJDK17U-jdk_x64_windows_hotspot_17.0.4.1_1.zip succeeded.`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Start the git bash from SourceTree or directly through windows (not from the context menu within the project)
2. Delete your devonfw-ide-project/software/java folder as well as the ~/Downloads/devonfw-ide folder
3. cd to your project directory
4. run `devon ide update all`

### Comments/Hints:
It looks like a mapping is missing or an emulation is not working properly.

### Affected version:

* devonfw-ide 2023.03.003

**Comment by hohwille** [comment] 2023-04-24 08:31
@jan-vcapgemini thanks for reporting this bug.
Can you give further insights on this?
To me it looks as the problem is related to the actual Java version `17.0.5_8` vs. `17.0.4.1_1`.
I doubt that a different bash "randomly" resolves to such a different java version.
To me it looks more as if you have 2 different configs/setups and one is using a Java version that simply does not exist what would render this bug report as invalid...
Can you have a look, if we can close this as invalid or if you have further details to explain the bug?

**Comment by NicolasHauf** [comment] 2023-04-25 09:09
The bug is reproducable using sourcetree and the embedded git version 2.39.1. Using system git version 2.40.0 there is no bug.

**Comment by NicolasHauf** [comment] 2023-04-25 09:24
When using the normal git bash without sourcetree on version 2.39.1 there is also no bug.
The problem seems to be sourcetree opening the git bash in a special way.

**Comment by hohwille** [comment] 2023-05-02 07:16
Seems to be a real edge-case. As it works in normal git-bash, we can not do much about this as it is not a bug of devonfw-ide itself.
In case someone ever stumbles over a workaround to fix this for source-tree, please reopen and leave a comment so we can add it to our documentation.

**Closed by hohwille** 2023-05-02 07:16 UTC
Labels: bug
