### ISSUE TITLE
setup.bat attaches itself

### ISSUE THREAD

**Issue by felixvogel** [devonfw/ide#688] opened 2022-01-17 13:53 UTC
### Expected behavior

Installs everything correct.

### Actual behavior
Everything works fine until:

*** Setting up npm ***
npm is already installed at /c/projects/my-project/software/node/npm
bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1

After clicking Strg C:

Terminate batch job (Y/N)? N
The operation completed successfully.
The operation completed successfully.
Setup of devonfw-ide completed
Press any key to continue . . .

I'm not sure if everything is installed correctly now.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Installed Devonfw
2. Clicked on setup.bat
3. Inserted at Settings URL: "https://pl.nue.local.vm/gitlab/tools/developer/project-ide-settings.git#nue" eingegeben.

### Affected version:
2021.12.004

* OS: Windows
* Browser: Chrome

**Comment by hohwille** [comment] 2022-01-24 08:47
@felixvogel thanks for your feedback.
First of all: devonfw-ide is a script that runs the setup for you. If you interrupt it with [ctrl][c] you will end up with an incomplete installation what should be obvious. In most cases rerunning setup should "reapair" a broken or incomplete installation but if you happened to abort during extraction of a tool into the software folder then the tool might be present but not complete and devonfw-ide can not easily distinguish this case.

> npm is already installed at /c/projects/my-project/software/node/npm

This is because `node` already installs `npm` on the fly. So this is not a "bug".

> bash: warning: shell level (1000) too high, resetting to 1

This is surely a bug and I have not yet seen this before. Can you explain how to reproduce this?
@all can someone else reproduce this error?

**Comment by felixvogel** [comment] 2022-01-25 10:32
I followed the Installation guide.
I downloaded the newest version 2021.12.004 (I also tried it with "devonfw-ide-scripts-2021.12.003" which produced the same error)
Executed: git config --global http."https://pl.nue.local.vm".sslVerify false
Then I extracted the downloaded zip in a project folder under C://, and doubleclicked on the setup.bat
(I was told that another one from my team had the same error)

**Comment by hohwille** [comment] 2022-01-28 21:02
@felixvogel thanks for your feedback.
Did you read the instructions?
https://github.com/devonfw/ide/blob/master/documentation/setup.asciidoc#install
You shall never directly install to `C://` as windows as restricted permissions and disallows scripts to directly create folders in `C:/` for good reasons. Can you create a folder `C:/projects` with UAC permission confirmation and inside create a folder for your project (without any whitespace in the name)?
Then extract the archive there.
BTW: The release is not a ZIP but a *.tar.gz file. However, "devonfw-ide-scripts-2021.12.003" sounds just fine and I am sure you downloaded the right thing as there is no ZIP with that filename part.

**Comment by felixvogel** [comment] 2022-01-31 07:36
Yes it was a *.tar.gz and with extracted under a project under C.// I meant I created a folder C://projects/my-project and in my-project I extracted the files. Sorry for the confusion.

**Comment by felixvogel** [comment] 2022-01-31 12:12
With the new version .005 it works fine, thank you.

**Comment by hohwille** [comment] 2022-02-21 17:25
Thanks for feedback and confirmation.
As we did not change anything in regard to this issue I am still closing as "rejected".

**Closed by hohwille** 2022-02-21 17:25 UTC
Labels: bug
