### ISSUE TITLE
Incorrect IntelliJ startup

### ISSUE THREAD

**Issue by ninjamode** [devonfw/ide#165] opened 2019-08-02 07:19 UTC
Category: Bug
Severity: Low

Expected behaviour: IntelliJ "Stop" button works
Actual/current behaviour: IntelliJ "Stop" button does not work

Startup of IntelliJ through software/intellij/idea file is incorrect and prevents signet propagation. This results in the stop button not working properly (IntelliJ also prints a warning to the event log).

See https://intellij-support.jetbrains.com/hc/en-us/articles/360004770440

I think this problem exists on all UNIX platforms, can't test it though. More technical details are available through the link.

For Macs, replacing
`'${DEVON_IDE_HOME}/software/intellij/IntelliJ.app/Contents/MacOS/idea' \$@`
with 
`open '${DEVON_IDE_HOME}/software/intellij/IntelliJ.app' --args \$@`
solves the problem, but does not work on Linux.

Capgemini Devon 3.0.0 on macOS 10.14.6

**Comment by hohwille** [comment] 2019-08-02 16:22
@ninjamode thanks for this valuable feedback.
However, I have to admit that I am not an IntelliJ user. I just created an IntelliJ commandlet as a starting point since we have many users that prefer IntelliJ. I personally use Eclipse and for client development I can arrage with VS Code. I was not yet aware of a "Stop" button in IntelliJ...

So with your constructive hints, I will try to improve but this is not on my priority list.
Currently I am doing all my best to finally get an official (non-beta) release out and if IntelliJ is working poorly that is the way it is. If someone wants to support and speed up, Pull-Requests are of course most welcome.

**Comment by hohwille** [comment] 2019-08-02 17:19
I also figured out that IntelliJ has a very strange workspace concept. So if I launch IntelliJ in another devon-ide installation, it still opens the project from the previous launch. This seems pretty much nuts to me.

So to make this really usable and behave sane a lot of small tweaks seems necessary.

**Comment by tobka777** [comment] 2021-07-01 12:12
I tried to reproduce this error with a simple java code.
```
import java.util.concurrent.TimeUnit;
public class Main {
    public static void main(String[] args) throws InterruptedException {
        TimeUnit.MINUTES.sleep(1);
    }
}
```

In both cases I can stop the program and I get: `Process finished with exit code 130 (interrupted by signal 2: SIGINT)`

Maybe Intellij change something in their code or we in our code...

**Comment by hohwille** [comment] 2021-07-26 10:32
@tobka777 thanks for restest and feedback.
I am hence closing this issue. In case someone still exepriences some error like this:
Simply add details explaining the error and how you reproduce it and reopen.

**Closed by hohwille** 2021-07-26 10:32 UTC
Labels: bug, commandlet, enhancement, help wanted, intellij, settings, software
