### ISSUE TITLE
Portable Intellij

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#1109] opened 2023-04-16 10:40 UTC
Just from my try outs it seems that there are some parts of existing installations shared of the devonfw intellij installation. I didn't had any trouble so far, but have seen, that my imported projects history and "latest state" of intellij seems to be shared across devonfw intellij installations.

I have found this: https://github.com/portapps/intellij-idea-community-portable/blob/master/main.go#L40 which might be a good hint to properly configure intellij portable. I haven't found this kind of configuration yet in the devonfw commandlet. So might be worth to think about enhancing the current setup.

**Comment by hohwille** [comment] 2023-04-24 08:24
I just analyzed this and found it is a duplicate of #1080 that has already been fixed and released. Hence closing.

**Closed by hohwille** 2023-04-24 08:24 UTC
Labels: duplicate, enhancement, software
