### ISSUE TITLE
Folder ${M2_REPO} gets created

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#706] opened 2022-02-21 17:32 UTC
### Expected behavior

All maven artifacts should go to the local maven repo configured via `devon.properties` (by default `$DEVON_IDE_HOME/conf/.m2/repository` but can also be changed to e.g. `~/.m2/repository` via `devon.properties`).

### Actual behavior

For some odd reason some tool or script causes a folder named `${M2_REPO}` being created in the top-level IDE installation `$DEVON_IDE_HOME`).

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create a devonfw-ide installation and run setup
2. Use this IDE to work with maven and eclipse in your project
3. at some point (exact steps for 2. still unclear) this magic `${M2_REPO}` folder appears and is filled with some maven artifacts.

### Comments/Hints:

Seems as if at some point `${M2_REPO}` is used as variable but does not properly get resolved leading to the fact that it is used as relative path for the maven repository created as folder.

### Affected version:

* OS: happened both on Windows and Mac

**Comment by tobka777** [comment] 2022-03-07 11:25
I have been able to reproduce the problem.
To do this, I have clone the project https://github.com/devonfw-sample/devon4quarkus-reference.git and run `mvn install`.
I have observed that the ~/.m2 folder is created when the tests run.
It seems to be an issue when using Quarkus tests. 
I found the following issue about this:
https://github.com/quarkusio/quarkus/issues/9505

With settings, you can add an option to the command to read the settings. Then it seems to work.
`devon mvn install --settings=$DEVON_IDE_HOME/conf/.m2/settings.xml`
Alternative `-Dmaven.settings=` should work also.

Now I am getting an error: `Caused by: java.lang.IllegalStateException: Please configure the datasource URL for the default datasource or ensure the Docker daemon is up and running.` Maybe this is project related, but I dont know.

What do you think about it?

**Comment by maybeec** [comment] 2022-03-07 18:35
I have seen similar issues just working on cobigen.
I am not sure whether it's a quarkus thing. Possibly some Maven or junit issue not resolving the variable. Anyhow I could not find a way to reproduce this issue. Nice that you found one! We need to have a closer look at it

**Comment by alfeilex** [comment] 2022-06-23 15:41
The problem is caused because the ${M2_REPO} variable is not resolved in conf/.m2/repository. This creates a folder with the same name as the variable when adding Maven dependencies in Eclipse. 

I could fix the bug by updating the following M2E Plugin.

**M2E - POM Editor using LemMinX language Server**

**Closed** 2022-06-28 14:06 UTC
Labels: bug, Team_IDE, Prio high

**Comment by tobka777** [comment] 2022-06-28 14:07
Thank you @alfeilex for the analysis and the fix 👍
