### ISSUE TITLE
custom evironment variables from devon.properties not available in IDE (e.g. Eclipse)

### ISSUE THREAD

**Issue by fdcg** [devonfw/ide#493] opened 2020-11-04 09:59 UTC
### Expected behavior

As a developer, I want to use correct settings in Eclipse IDE.

### Actual behavior
Starting Eclipse with the command 'devon eclipse' in a workspace folder or staring with the generated start script do not set devon environment variables.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)
1. Use devon environment variables in the maven settings.xml e.g. for the url of a repository server.
2. Start Eclipse with the generated start script
3. In Eclipse import a new maven project with File -> Import -> Excisting Maven Project
4. The imported project has no maven dependencies in the build path because the url variable in the maven settings can not be found.  

### Affected version:

* OS: Windows 10
* devon IDE: 2020.08.001

**Comment by hohwille** [comment] 2020-11-30 08:37
I can not reproduce this bug and it is working for many others including me.
Hence, you need to provide additional details about your environment.
So your m2e (maven eclipse plugin) can not resolve dependencies. This can have arbitrary reasons (no internet, settings.xml broken, etc.). You would need to provide the error/exception details.
Does maven resolve the dependencies on the commandline (`devon`, `mvn clean install`)?

**Comment by hohwille** [comment] 2020-12-14 09:01
@fdcg could you comment on this issue? Otherwise we will have to close it as invalid since we can not proceed without further details.

**Comment by hohwille** [comment] 2020-12-14 09:45
@fdcg and I analyzed this problem together:
* it only occurrs on windows
* it only happens for more specific variables
* the problem is that `devon eclipse` will set the variables in `bash` and not in `cmd`. When it then calls `eclipse` or any other process from that `bash` only exported variables apear to be set in that process (here eclipse).
* therefore a quick workaround is to add "export " before these variables in you `devon.properties` file.
* however, we should find a better solution and IMHO launching `devon eclipse` (or calling any other IDE via devon) should make all variables from `devon.properties` visible.
* to avoid exporting all variables in the users shell what conflicts with #5, we may simply only export whenever we call a devonfw subcommand.

**Closed** 2020-12-14 13:08 UTC
Labels: bug, eclipse, scripts
