### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by dario-rodriguez** [devonfw/ide#286] opened 2019-10-23 18:30 UTC
As a develop, when I was using the devon-ide it seemed to me that the commands were too long. So, can we create some aliases for the commands? 

For example:
`devon java create` -> `devon j c`

It's not a replacement, is a shorter way of typing the commands, but the other one is still available. It would be useful for avanced user in order to speed up their work.

Is it possible to do in an easy way or it would need a lot of rework ?

**Comment by hohwille** [comment] 2019-10-29 09:06
Nice suggestion. IMHO the easiest approach to do that is to consistently switch to `case` statements for the CLI parsing in the commandlets so we can do something like:
```
case "${1}" in
  create|c)
    doCreateProject;;
  ...
esac
```

For the commandlets itself (java, node, dotnet, mvn, ng, etc.) I am not yet entirely sure. We will add more commandlets in the future and the integration of those is entirely generic.
That means if we allow to call a commandlet by just the first letter, we will quickly run into conflicts if two commandlets share the same prefix. E.g. `devon n ...` could trigger `ng` or `node`. Otherwise if we only accept shortened prefixes that are unique, then in the current release `devon e` will start eclipse and later if commandlet `eth` would be added then the same `devon e` command would fail in the next release as it is ambiguous.

**Comment by hohwille** [comment] 2019-10-29 09:07
Maybe better we could install real alias so `devon4j` is a shortcut for `devon java` and `devon4node` is a shortcut for `devon node`. However, `devon4node` already is a script existing that behaves different so this would also conflict.

**Comment by hohwille** [comment] 2019-11-01 07:48
IMHO if we implement autocompletion (#287) the priority for shortened commands is very low. I have to type less with autocompletion what should serve the same goal but I am still more explicit and understand what I am calling (`devon c j` - What's this?).

**Comment by markusschuh** [comment] 2019-11-01 08:24
I fully agree that autocomplete is the priority. 

Using such shortcuts in scripts were bad style anyway.

Abbreviated sub commands has a high potential to cause conflicts later and to produce mix ups. 

Anybody who prefers short commands should be able to create his/her **own** alias additions inside **personal** bash initialization file. Alias need to be only one word - but this can be even shorter to type like e.g.
```
alias djc='devon java create'
```

**Comment by hohwille** [comment] 2019-12-13 17:38
After the comment from @markusschuh I will rather close this issue as wontfix (resp. duplicate of #287). If you disagree please give some arguments and we can reopen.

**Closed by hohwille** 2019-12-13 17:38 UTC
Labels: enhancement
